aa-bc:
  authenticationEndpoint: http://rossum.knbit.edu.pl:41001/authenticate
  authorizationEndpoint: http://rossum.knbit.edu.pl:41001/authorize
  authHeaderKey: knbit-aa-auth
spring:
  profiles:
    active: development
