aa-bc:
  loginEndpoint: http://rossum.knbit.edu.pl:41001/login
  authenticationEndpoint: http://rossum.knbit.edu.pl:41001/authenticate
  authorizationEndpoint: http://rossum.knbit.edu.pl:41001/authorize
  authHeaderKey: knbit-aa-auth

notification-bc:
  knbitEmail: knbit@email.com
  knbitPassword: knbitPass
  notifyMembersEndpoint: http://notification-bc:41004/mail
  notifyAllMembersEndpoint: http://notification-bc:41004/mail?sendToAllBitMembers=true

spring:
  profiles:
    active: development
